# Windows Service Installation Script for GADA
# Generated by GADA Installer

param(
    [string]$ServiceName = "{{service_name}}",
    [string]$DisplayName = "{{display_name}}",
    [string]$Description = "GitHub Deploy Assistant - DevOps自动化部署工具",
    [string]$InstallDir = "{{working_dir}}",
    [string]$NodePath = "{{node_path}}",
    [string]$MainScript = "{{main_script}}",
    [string]$LogDir = "{{log_dir}}",
    [string]$ConfigDir = "{{config_dir}}",
    [string]$User = "{{user}}"
)

# 错误处理
$ErrorActionPreference = "Stop"

# 颜色定义
$ColorGreen = "Green"
$ColorYellow = "Yellow"
$ColorRed = "Red"
$ColorCyan = "Cyan"
$ColorGray = "Gray"

# 日志函数
function Write-Log {
    param(
        [string]$Message,
        [string]$Color = "White",
        [string]$Level = "INFO"
    )
    $Timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    Write-Host "[$Timestamp] [$Level] $Message" -ForegroundColor $Color
}

function Write-Success {
    param([string]$Message)
    Write-Log -Message $Message -Color $ColorGreen -Level "SUCCESS"
}

function Write-Warning {
    param([string]$Message)
    Write-Log -Message $Message -Color $ColorYellow -Level "WARNING"
}

function Write-Error {
    param([string]$Message)
    Write-Log -Message $Message -Color $ColorRed -Level "ERROR"
}

function Write-Info {
    param([string]$Message)
    Write-Log -Message $Message -Color $ColorCyan -Level "INFO"
}

function Write-Debug {
    param([string]$Message)
    Write-Log -Message $Message -Color $ColorGray -Level "DEBUG"
}

# 检查管理员权限
function Test-Administrator {
    $currentPrincipal = New-Object Security.Principal.WindowsPrincipal([Security.Principal.WindowsIdentity]::GetCurrent())
    return $currentPrincipal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
}

# 检查服务是否存在
function Test-ServiceExists {
    param([string]$Name)
    try {
        $service = Get-Service -Name $Name -ErrorAction SilentlyContinue
        return ($null -ne $service)
    }
    catch {
        return $false
    }
}

# 停止并删除服务
function Remove-ServiceSafe {
    param([string]$Name)
    
    if (Test-ServiceExists -Name $Name) {
        Write-Info "停止服务: $Name"
        
        # 停止服务
        $service = Get-Service -Name $Name
        if ($service.Status -ne "Stopped") {
            Stop-Service -Name $Name -Force -ErrorAction SilentlyContinue
            Start-Sleep -Seconds 3
        }
        
        # 删除服务
        Write-Info "删除服务: $Name"
        sc.exe delete $Name | Out-Null
        Start-Sleep -Seconds 2
        
        Write-Success "服务已删除: $Name"
    } else {
        Write-Info "服务不存在: $Name"
    }
}

# 安装服务
function Install-Service {
    Write-Info "开始安装GADA Windows服务..."
    
    # 显示配置信息
    Write-Debug "服务名称: $ServiceName"
    Write-Debug "显示名称: $DisplayName"
    Write-Debug "安装目录: $InstallDir"
    Write-Debug "Node路径: $NodePath"
    Write-Debug "主脚本: $MainScript"
    Write-Debug "日志目录: $LogDir"
    Write-Debug "配置目录: $ConfigDir"
    
    # 检查Node.js
    if (-not (Test-Path $NodePath)) {
        Write-Error "Node.js未找到: $NodePath"
        Write-Warning "请确保Node.js已正确安装并添加到PATH"
        exit 1
    }
    
    # 检查主脚本
    if (-not (Test-Path $MainScript)) {
        Write-Error "主脚本未找到: $MainScript"
        Write-Warning "请确保GADA已正确安装"
        exit 1
    }
    
    # 创建目录
    Write-Info "创建目录..."
    $directories = @($InstallDir, $LogDir, $ConfigDir)
    foreach ($dir in $directories) {
        if (-not (Test-Path $dir)) {
            New-Item -ItemType Directory -Path $dir -Force | Out-Null
            Write-Debug "创建目录: $dir"
        }
    }
    
    # 删除现有服务
    Remove-ServiceSafe -Name $ServiceName
    
    # 创建服务
    Write-Info "创建Windows服务..."
    
    # 构建服务参数
    $serviceParams = @{
        Name = $ServiceName
        BinaryPathName = "`"$NodePath`" `"$MainScript`" --service"
        DisplayName = $DisplayName
        Description = $Description
        StartupType = "Automatic"
    }
    
    # 创建服务
    try {
        New-Service @serviceParams -ErrorAction Stop | Out-Null
        Write-Success "服务创建成功: $ServiceName"
    }
    catch {
        Write-Error "服务创建失败: $_"
        
        # 尝试使用sc.exe
        Write-Info "尝试使用sc.exe创建服务..."
        $scCommand = "sc.exe create `"$ServiceName`" binPath= `"`"$NodePath`" `"$MainScript`" --service`" DisplayName= `"$DisplayName`" start= auto"
        Invoke-Expression $scCommand
        
        if ($LASTEXITCODE -ne 0) {
            Write-Error "sc.exe创建服务也失败"
            exit 1
        }
        
        Write-Success "服务通过sc.exe创建成功"
    }
    
    # 配置服务恢复选项
    Write-Info "配置服务恢复选项..."
    $recoveryParams = @{
        Name = $ServiceName
        FirstFailureAction = "Restart"
        SecondFailureAction = "Restart"
        ThirdFailureAction = "Restart"
        RestartDelay = 60000  # 60秒后重启
        ResetPeriod = 86400   # 24小时重置失败计数
    }
    
    try {
        Set-Service @recoveryParams -ErrorAction SilentlyContinue
        Write-Success "服务恢复选项配置成功"
    }
    catch {
        Write-Warning "服务恢复选项配置失败: $_"
    }
    
    # 设置服务描述
    Write-Info "设置服务描述..."
    $regPath = "HKLM:\SYSTEM\CurrentControlSet\Services\$ServiceName"
    if (Test-Path $regPath) {
        Set-ItemProperty -Path $regPath -Name "Description" -Value $Description -ErrorAction SilentlyContinue
        Write-Debug "服务描述已设置"
    }
    
    # 启动服务
    Write-Info "启动服务..."
    try {
        Start-Service -Name $ServiceName -ErrorAction Stop
        Write-Success "服务启动成功"
        
        # 等待服务状态
        Start-Sleep -Seconds 3
        $service = Get-Service -Name $ServiceName
        Write-Info "服务状态: $($service.Status)"
        
    }
    catch {
        Write-Error "服务启动失败: $_"
        Write-Warning "请手动启动服务或检查错误日志"
    }
    
    # 创建卸载脚本
    Create-UninstallScript
    
    Write-Success "`n🎉 GADA Windows服务安装完成！"
    Write-Info "服务名称: $ServiceName"
    Write-Info "管理命令:"
    Write-Info "  • 启动服务: Start-Service -Name $ServiceName"
    Write-Info "  • 停止服务: Stop-Service -Name $ServiceName -Force"
    Write-Info "  • 重启服务: Restart-Service -Name $ServiceName"
    Write-Info "  • 查看状态: Get-Service -Name $ServiceName"
    Write-Info "`n📝 日志位置: $LogDir"
    Write-Info "⚙️  配置文件: $ConfigDir"
}

# 创建卸载脚本
function Create-UninstallScript {
    $uninstallScript = @"
# GADA Windows服务卸载脚本
# 运行: powershell -ExecutionPolicy Bypass -File "$($InstallDir)\uninstall-service.ps1"

`$ServiceName = "$ServiceName"

Write-Host "正在卸载GADA服务..." -ForegroundColor Cyan

# 停止服务
try {
    `$service = Get-Service -Name `$ServiceName -ErrorAction SilentlyContinue
    if (`$service -and `$service.Status -ne "Stopped") {
        Write-Host "停止服务..." -ForegroundColor Yellow
        Stop-Service -Name `$ServiceName -Force -ErrorAction SilentlyContinue
        Start-Sleep -Seconds 3
    }
}
catch {
    Write-Host "停止服务时出错: `$_" -ForegroundColor Red
}

# 删除服务
try {
    Write-Host "删除服务..." -ForegroundColor Yellow
    sc.exe delete `$ServiceName 2>`$null
    Write-Host "服务已删除" -ForegroundColor Green
}
catch {
    Write-Host "删除服务时出错: `$_" -ForegroundColor Red
}

Write-Host "`n🎉 GADA服务卸载完成！" -ForegroundColor Green
Write-Host "如果需要完全清理，请手动删除目录: $InstallDir" -ForegroundColor Gray
"@
    
    $uninstallPath = Join-Path $InstallDir "uninstall-service.ps1"
    Set-Content -Path $uninstallPath -Value $uninstallScript -Encoding UTF8
    Write-Debug "卸载脚本已创建: $uninstallPath"
}

# 主程序
try {
    Write-Host "`n🚀 GADA Windows服务安装程序" -ForegroundColor Cyan
    Write-Host "=" * 50 -ForegroundColor Gray
    
    # 检查管理员权限
    if (-not (Test-Administrator)) {
        Write-Error "需要管理员权限运行此脚本"
        Write-Warning "请以管理员身份运行PowerShell"
        exit 1
    }
    
    Write-Success "管理员权限检查通过"
    
    # 显示安装确认
    Write-Host "`n📋 安装配置:" -ForegroundColor Cyan
    Write-Host "  • 服务名称: $ServiceName" -ForegroundColor Gray
    Write-Host "  • 显示名称: $DisplayName" -ForegroundColor Gray
    Write-Host "  • 安装目录: $InstallDir" -ForegroundColor Gray
    Write-Host "  • 日志目录: $LogDir" -ForegroundColor Gray
    
    # 确认安装
    $confirm = Read-Host "`n确认安装? (Y/N)"
    if ($confirm -notmatch "^[Yy]") {
        Write-Host "安装已取消" -ForegroundColor Yellow
        exit 0
    }
    
    # 执行安装
    Install-Service
    
}
catch {
    Write-Error "安装过程中出现错误: $_"
    Write-Host "详细错误信息:" -ForegroundColor Red
    Write-Host $_.Exception -ForegroundColor Red
    Write-Host $_.ScriptStackTrace -ForegroundColor Gray
    exit 1
}